name = "ServerCore"
author = "Groundix"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aed58f6590767d2110aba35eef1ef44c41bb83408fdc56377d699cd9fe973bf2"

[versions]
minecraft = "1.19.4"
